import { BusinessSettings, ThemeConfig, HomepageSection, Activity, Course, Trip, GalleryItem, Review, FAQ } from "./types";
import { THEME_PRESETS } from "./theme-presets";

// ==============================================================================
// AUTHENTIC DIVING VISION CENTER - SHARM EL-SHEIKH CONFIGURATION
// ==============================================================================

export const AUTHORITATIVE_BUSINESS_NAME =
  process.env.NEXT_PUBLIC_BUSINESS_NAME || "Diving Vision Center";

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  business_name: AUTHORITATIVE_BUSINESS_NAME,
  tagline: "PADI 5-Star Dive Resort & Red Sea Expeditions",
  description: "Premier PADI 5-Star Dive Center based in Sharm El-Sheikh, Egypt. Specializing in daily boat safaris to Ras Mohammed, Straits of Tiran, SS Thistlegorm WW2 wreck, and certified diver education with elite safety standards.",
  logo_url: "",
  favicon_url: "",
  phone: "+20 100 892 4410",
  whatsapp_number: "201008924410",
  whatsapp_default_message: `Hello Diving Vision Sharm El-Sheikh, I would like to inquire about booking diving trips and courses.`,
  whatsapp_config: {
    phone_number: "201008924410",
    button_label: "WhatsApp Booking",
    default_message: `Hello Diving Vision Sharm El-Sheikh, I would like to inquire about booking diving trips and courses.`,
    is_enabled: true,
    position: "bottom-right",
    animation_intensity: "subtle",
    show_on_mobile: true,
    show_on_desktop: true,
  },
  email: "info@divingvisioncenter.com",
  address: "Peace Road, Naama Bay / Hadaba Promenade",
  city: "Sharm El-Sheikh",
  country: "Egypt",
  google_maps_url: "https://maps.google.com/?q=Sharm+El+Sheikh+Red+Sea+Diving",
  currency: "EUR",
  opening_hours: [
    { days: "Monday – Sunday", hours: "07:30 – 19:00" },
    { days: "Daily Boat Departures", hours: "08:00 – 16:30" },
    { days: "Night Dives (House Reef)", hours: "18:30 – 21:30 (By Reservation)" },
  ],
  social_links: {
    instagram: "https://instagram.com/divingvisioncenter",
    facebook: "https://facebook.com/divingvisioncenter",
    tiktok: "https://tiktok.com/@divingvisioncenter",
    tripadvisor: "https://tripadvisor.com",
  },
  last_published_at: "2026-09-10T00:00:00.000Z",
  last_modified_at: "2026-09-10T00:00:00.000Z",
  has_unpublished_changes: false,
};

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSection[] = [
  {
    id: "sec-hero",
    section_key: "hero",
    name: "Hero Showcase",
    title: "Discover the Red Sea's Ultimate Depths.",
    subtitle: "PADI 5-Star Dive Resort in Sharm El-Sheikh. World-class coral reefs, legendary WW2 wrecks, and daily private boat safaris.",
    badge: "PADI 5-Star Dive Center #34281",
    is_enabled: true,
    display_order: 1,
    has_unpublished_changes: false,
    settings: {
      water_temp: "28°C / 82°F",
      visibility: "35m+ Crystal",
      guide_ratio: "Max 1:4 Ratio",
      gear_tier: "Scubapro & Aqualung",
    },
  },
  {
    id: "sec-narrative",
    section_key: "narrative",
    name: "About Diving Vision",
    title: "Over 18 Years of Red Sea Marine Excellence.",
    subtitle: "From beginner Discover Scuba sessions to technical wreck explorations at SS Thistlegorm, our certified master instructors prioritize safety, conservation, and uncompromised dive time.",
    badge: "The Diving Vision Standard",
    is_enabled: true,
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "sec-trips",
    section_key: "trips",
    name: "Boat Safaris & Daily Trips",
    title: "Daily Boat Safaris & Wreck Expeditions",
    subtitle: "Cruise aboard our spacious double-deck dive yachts with freshly prepared hot lunch, shade sundecks, and top-tier safety gear.",
    badge: "Daily Boat Safaris",
    is_enabled: true,
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "sec-activities",
    section_key: "activities",
    name: "Signature Experiences",
    title: "Diving & Snorkeling Experiences",
    subtitle: "Tailored dive programs for certified divers, non-certified beginners, and marine enthusiasts of all ages.",
    badge: "Top Dive Adventures",
    is_enabled: true,
    display_order: 4,
    has_unpublished_changes: false,
  },
  {
    id: "sec-courses",
    section_key: "courses",
    name: "PADI Diver Academy",
    title: "Certified PADI Courses & Specialties",
    subtitle: "Earn your lifetime international scuba certification in the warm, crystal-clear waters of Sharm El-Sheikh.",
    badge: "PADI Certified Training",
    is_enabled: true,
    display_order: 5,
    has_unpublished_changes: false,
  },
  {
    id: "sec-why-us",
    section_key: "why_us",
    name: "Why Choose Us",
    title: "Engineered for Safety, Luxury & Conservation",
    subtitle: "Why divers from around the world choose Diving Vision as their home base in Sharm El-Sheikh.",
    badge: "Our Commitment",
    is_enabled: true,
    display_order: 6,
    has_unpublished_changes: false,
  },
  {
    id: "sec-gallery",
    section_key: "gallery",
    name: "Underwater Visual Gallery",
    title: "Moments from the Red Sea Abyss",
    subtitle: "Real underwater encounters captured during our daily safaris in Ras Mohammed, Tiran, and Dahab.",
    badge: "Real Marine Encounters",
    is_enabled: true,
    display_order: 7,
    has_unpublished_changes: false,
  },
  {
    id: "sec-reviews",
    section_key: "reviews",
    name: "Guest Reviews",
    title: "Loved by Divers Worldwide",
    subtitle: "Read genuine feedback from international travelers, underwater photographers, and newly certified divers.",
    badge: "5.0 ★ Rated on TripAdvisor & Google",
    is_enabled: true,
    display_order: 8,
    has_unpublished_changes: false,
  },
  {
    id: "sec-faqs",
    section_key: "faqs",
    name: "Frequently Asked Questions",
    title: "Everything You Need to Know",
    subtitle: "Answers to common questions regarding gear rental, national park fees, dive prerequisites, and pickup transfers.",
    badge: "Help & Information",
    is_enabled: true,
    display_order: 9,
    has_unpublished_changes: false,
  },
  {
    id: "sec-booking",
    section_key: "booking",
    name: "Instant Reservation & Concierge",
    title: "Plan Your Red Sea Expedition",
    subtitle: "Reserve your dive slots online. Free hotel transfers across Sharm El-Sheikh, zero deposit required to check availability.",
    badge: "Direct Reservation",
    is_enabled: true,
    display_order: 10,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_TRIPS: Trip[] = [
  {
    id: "trip-ras-mohammed",
    title: "Ras Mohammed National Park Boat Safari",
    destination: "Shark & Yolanda Reefs, Anemone City",
    duration: "Full Day (08:00 – 16:30)",
    price: 65,
    currency: "EUR",
    group_size_max: 16,
    boat_name: "M/Y Vision Deluxe",
    image_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1600&auto=format&fit=crop",
    description: "The crown jewel of the Red Sea. Dive the dramatic 800m drop-off at Shark & Yolanda Reefs, home to massive schools of barracuda, giant trevallies, and vibrant soft coral gardens.",
    highlights: [
      "2 Guided Boat Dives at Premier Marine Reserve Sites",
      "Freshly prepared buffet lunch cooked onboard by yacht chef",
      "Unlimited hot & soft drinks throughout the cruise",
      "Complimentary pickup & drop-off from any Sharm hotel",
      "Nitrox 32% available for certified enriched air divers",
    ],
    schedule_details: "Daily departures from Travco Marina at 08:30 AM. Returns at 16:30 PM.",
    status: "published",
    display_order: 1,
    has_unpublished_changes: false,
  },
  {
    id: "trip-thistlegorm",
    title: "SS Thistlegorm WW2 Shipwreck Expedition",
    destination: "Sha'ab Ali, Gulf of Suez",
    duration: "Full Day Early Safari (05:00 – 17:00)",
    price: 145,
    currency: "EUR",
    group_size_max: 12,
    boat_name: "M/Y Vision Explorer",
    image_url: "https://images.unsplash.com/photo-1560275619-4662e36fa65c?q=80&w=1600&auto=format&fit=crop",
    description: "Ranked the #1 wreck dive in the world. Explore the historic 128-meter British WW2 cargo vessel loaded with Bedford trucks, BSA motorbikes, train locomotives, and aircraft munitions.",
    highlights: [
      "2 Deep Guided Dives (External structure & Cargo hold penetration)",
      "Requires Advanced Open Water or 20+ logged dives",
      "Includes hot breakfast & full afternoon buffet lunch onboard",
      "Detailed historical briefing with 3D wreck layout maps",
      "Includes all marine national park entry permits",
    ],
    schedule_details: "Departures on Mondays, Wednesdays & Saturdays. Early hotel transfer at 05:00 AM.",
    status: "published",
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "trip-tiran-island",
    title: "Straits of Tiran Coral Reef Safari",
    destination: "Jackson, Woodhouse, Thomas & Gordon Reefs",
    duration: "Full Day (08:00 – 16:30)",
    price: 65,
    currency: "EUR",
    group_size_max: 16,
    boat_name: "M/Y Vision Deluxe",
    image_url: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?q=80&w=1600&auto=format&fit=crop",
    description: "World-famous drift dives across four distinct offshore coral pinnacles. Expect massive gorgonian sea fans, passing reef sharks, turtles, and pristine coral visibility exceeding 40 meters.",
    highlights: [
      "2 Guided Offshore Boat Dives + Optional 3rd Dive",
      "Spectacular Jackson Reef Red Anemone garden & Lovilla shipwreck",
      "Freshly prepared buffet lunch & fruit platters",
      "Spacious shaded dive deck with personal equipment lockers",
    ],
    schedule_details: "Daily departures from Shark's Bay / Naama Marina at 08:30 AM.",
    status: "published",
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "trip-dahab-blue-hole",
    title: "Dahab Blue Hole & Canyon Land Safari",
    destination: "Dahab Coast & Marine Protected Area",
    duration: "Full Day Overland (07:30 – 17:30)",
    price: 85,
    currency: "EUR",
    group_size_max: 10,
    boat_name: "Air-Conditioned 4x4 Overland",
    image_url: "https://images.unsplash.com/photo-1544551763-77ef2d0cf96c?q=80&w=1600&auto=format&fit=crop",
    description: "Combine world-famous shore diving with a scenic Sinai desert safari. Dive the breathtaking 100m Blue Hole submarine sinkhole and the deep geological fissure of The Canyon.",
    highlights: [
      "2 Guided Shore Dives at Blue Hole & The Canyon",
      "Bedouin seaside lunch at authentic coastal camp",
      "Free time for shopping in Dahab's vibrant promenade",
      "Air-conditioned private transfer through Sinai mountains",
    ],
    schedule_details: "Operated on Tuesdays & Fridays. Hotel pickup at 07:30 AM.",
    status: "published",
    display_order: 4,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_ACTIVITIES: Activity[] = [
  {
    id: "act-intro-dive",
    title: "Discover Scuba Diving (Introductory Experience)",
    category: "Beginner Experience",
    duration: "1 Day (Includes 2 Dives)",
    difficulty: "Beginner (No Experience Required)",
    price: 75,
    currency: "EUR",
    image_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1600&auto=format&fit=crop",
    description: "Never dived before? Experience the magic of breathing underwater in total safety. Includes 1-on-1 instructor guidance, full equipment, and boat trip with lunch.",
    highlights: [
      "Dedicated 1-on-1 PADI Master Instructor by your side",
      "Safety briefing & shallow water practice in calm bay",
      "2 Open water reef dives up to 6–10m depth with tropical fish",
      "Full rental equipment (wetsuit, mask, fins, BCD, regulator) included",
    ],
    status: "published",
    display_order: 1,
    has_unpublished_changes: false,
  },
  {
    id: "act-daily-certified-pack",
    title: "Certified Diver Daily Package (2 Boat Dives)",
    category: "Certified Divers",
    duration: "Full Day (2 Dives)",
    difficulty: "Certified Diver (Open Water+)",
    price: 55,
    currency: "EUR",
    image_url: "https://images.unsplash.com/photo-1560275619-4662e36fa65c?q=80&w=1600&auto=format&fit=crop",
    description: "The classic Sharm dive day. 2 guided boat dives to the best reefs of Ras Mohammed or Tiran Island with small guide-to-diver ratios and top rental gear.",
    highlights: [
      "12L Aluminum tanks with calibrated weights included",
      "Professional dive guide certified in marine biology & rescue",
      "Discounts available for multi-day dive packages (3, 5, or 10 days)",
      "Optional 3rd dive available on the boat for €20",
    ],
    status: "published",
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "act-night-dive",
    title: "Bioluminescent Night Dive (House Reef / Boat)",
    category: "Specialty Dive",
    duration: "2.5 Hours",
    difficulty: "Advanced or Open Water with Night Experience",
    price: 45,
    currency: "EUR",
    image_url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?q=80&w=1600&auto=format&fit=crop",
    description: "Watch the coral reef transform after dusk. Experience hunting lionfish, giant moray eels on the prowl, sleeping parrotfish in mucous cocoons, and glowing bioluminescence.",
    highlights: [
      "High-power primary underwater dive torch + backup glow beacon",
      "Full safety briefing on night navigation and light signals",
      "In-depth guide briefing on nocturnal marine behavior",
    ],
    status: "published",
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "act-snorkeling-boat",
    title: "VIP Guided Snorkeling & Island Cruise",
    category: "Non-Divers & Families",
    duration: "Full Day (08:00 – 16:30)",
    difficulty: "All Ages Welcome",
    price: 35,
    currency: "EUR",
    image_url: "https://images.unsplash.com/photo-1544551763-77ef2d0cf96c?q=80&w=1600&auto=format&fit=crop",
    description: "Perfect for non-divers, friends, and families. Cruise along Ras Mohammed or White Island with our dedicated snorkel guide, life jackets, and hot buffet lunch.",
    highlights: [
      "Professional snorkel guide leading reef exploration",
      "High-grade masks, snorkels, fins, and floatation vests provided",
      "Stop at the magical White Island sandbank for photos",
      "Delicious hot lunch buffet and free hotel transfers",
    ],
    status: "published",
    display_order: 4,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_COURSES: Course[] = [
  {
    id: "course-padi-open-water",
    title: "PADI Open Water Diver Certification",
    level: "Beginner Certification",
    prerequisites: "10+ Years Old, Basic Swimming Ability",
    duration_days: 3,
    price: 340,
    currency: "EUR",
    certification_agency: "PADI 5-Star Certified",
    image_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1600&auto=format&fit=crop",
    overview: "The world's most recognized scuba certification. Qualifies you to dive independently with a buddy anywhere in the world up to 18 meters (60 feet) for life.",
    modules: [
      "PADI digital eLearning theory (complete on your phone/tablet)",
      "Confined water skills practice in shallow sheltered bay",
      "4 Open water ocean dives at Sharm's beautiful coral reefs",
      "Official PADI international digital eCard certification",
    ],
    includes: [
      "All full equipment rental throughout the course",
      "Official PADI learning materials and certification fees",
      "Logbook and private boat transfers",
      "Instructor fees and pool/confined water sessions",
    ],
    status: "published",
    display_order: 1,
    has_unpublished_changes: false,
  },
  {
    id: "course-padi-advanced",
    title: "PADI Advanced Open Water Diver",
    level: "Intermediate Certification",
    prerequisites: "PADI Open Water Diver (or equivalent)",
    duration_days: 2,
    price: 260,
    currency: "EUR",
    certification_agency: "PADI 5-Star Certified",
    image_url: "https://images.unsplash.com/photo-1560275619-4662e36fa65c?q=80&w=1600&auto=format&fit=crop",
    overview: "Take your diving to the next level. Complete 5 adventure dives to increase your depth limit to 30 meters (100 feet) and master navigation and buoyancy.",
    modules: [
      "Mandatory Deep Dive (up to 30m depth exploration)",
      "Mandatory Underwater Navigation Dive (Compass & natural navigation)",
      "Choice of 3 Electives: Wreck Dive, Peak Performance Buoyancy, Drift Dive, or Night Dive",
      "No final exam – purely practical diving and skill mastery",
    ],
    includes: [
      "5 adventure boat dives with Master Instructor",
      "PADI Advanced eLearning & international certification card",
      "Tanks, weights, and boat safari lunch included",
    ],
    status: "published",
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "course-padi-nitrox",
    title: "PADI Enriched Air (Nitrox) Specialty",
    level: "Specialty Course",
    prerequisites: "PADI Open Water Diver (or equivalent)",
    duration_days: 1,
    price: 120,
    currency: "EUR",
    certification_agency: "PADI 5-Star Certified",
    image_url: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?q=80&w=1600&auto=format&fit=crop",
    overview: "PADI's most popular specialty. Learn to dive with gas blends containing up to 40% oxygen to extend your bottom time and reduce surface intervals on boat safaris.",
    modules: [
      "Oxygen exposure management and dive computer setup",
      "Analyzing oxygen content in scuba cylinders with digital analyzer",
      "Fill log documentation and cylinder labeling procedures",
      "Can be completed in 1 day with or without practical dives",
    ],
    includes: [
      "PADI Enriched Air digital eLearning",
      "Use of professional digital oxygen analyzer",
      "Official PADI Nitrox certification eCard",
    ],
    status: "published",
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "course-padi-rescue",
    title: "PADI Rescue Diver & Emergency First Response",
    level: "Advanced Safety & Rescue",
    prerequisites: "Advanced Open Water + EFR (First Aid)",
    duration_days: 3,
    price: 390,
    currency: "EUR",
    certification_agency: "PADI 5-Star Certified",
    image_url: "https://images.unsplash.com/photo-1544551763-77ef2d0cf96c?q=80&w=1600&auto=format&fit=crop",
    overview: "Challenging and rewarding. Learn to anticipate, prevent, and manage diving emergencies both on the surface and underwater, becoming the most reliable buddy in any dive group.",
    modules: [
      "Self-rescue techniques and diver stress management",
      "Emergency oxygen administration & CPR / First Aid",
      "Panicked and unresponsive diver recovery protocols",
      "Realistic simulated open-water ocean rescue scenarios",
    ],
    includes: [
      "Full Rescue Diver eLearning materials and certification fees",
      "Emergency oxygen kit and rescue pocket mask training",
      "Comprehensive 3-day practical instruction",
    ],
    status: "published",
    display_order: 4,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_GALLERY: GalleryItem[] = [
  {
    id: "gal-shark-reef",
    title: "Shark & Yolanda Reef Wall",
    category: "Coral Reefs",
    image_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1600&auto=format&fit=crop",
    caption: "Vibrant soft coral drop-off in Ras Mohammed National Park",
    storage_path: "",
    status: "published",
    display_order: 1,
    has_unpublished_changes: false,
  },
  {
    id: "gal-thistlegorm-trucks",
    title: "SS Thistlegorm Cargo Hold",
    category: "Shipwrecks",
    image_url: "https://images.unsplash.com/photo-1560275619-4662e36fa65c?q=80&w=1600&auto=format&fit=crop",
    caption: "WW2 British Bedford trucks and BSA motorbikes preserved at 28 meters depth",
    storage_path: "",
    status: "published",
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "gal-sea-turtle",
    title: "Hawksbill Sea Turtle Glide",
    category: "Marine Encounters",
    image_url: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?q=80&w=1600&auto=format&fit=crop",
    caption: "Resident Hawksbill turtle feeding on soft corals at Jackson Reef, Tiran",
    storage_path: "",
    status: "published",
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "gal-dive-boat",
    title: "M/Y Vision Deluxe at Anchor",
    category: "Boat Safaris",
    image_url: "https://images.unsplash.com/photo-1544551763-77ef2d0cf96c?q=80&w=1600&auto=format&fit=crop",
    caption: "Our custom 28-meter dive yacht anchored in the calm waters of Ras Mohammed",
    storage_path: "",
    status: "published",
    display_order: 4,
    has_unpublished_changes: false,
  },
  {
    id: "gal-eagle-ray",
    title: "Spotted Eagle Ray in Blue",
    category: "Pelagic Life",
    image_url: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?q=80&w=1600&auto=format&fit=crop",
    caption: "A pair of spotted eagle rays cruising past Thomas Reef wall",
    storage_path: "",
    status: "published",
    display_order: 5,
    has_unpublished_changes: false,
  },
  {
    id: "gal-clownfish-anemone",
    title: "Red Sea Anemone City",
    category: "Coral Reefs",
    image_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1600&auto=format&fit=crop",
    caption: "Endemic Red Sea clownfish defending their magnificent sea anemone",
    storage_path: "",
    status: "published",
    display_order: 6,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_REVIEWS: Review[] = [
  {
    id: "rev-1",
    author_name: "Captain Marco Rossi",
    author_title: "Master Scuba Diver Trainer (Italy)",
    rating: 5,
    date: "2026-08-28",
    comment: "I have dived in Egypt for over 15 years, and Diving Vision is hands down the most professional operation in Sharm. The dive guides at Ras Mohammed and Thistlegorm gave the most thorough briefings I have seen. The boat food is top notch!",
    is_featured: true,
    status: "published",
    has_unpublished_changes: false,
  },
  {
    id: "rev-2",
    author_name: "Dr. Sarah Jenkins",
    author_title: "PADI Advanced Open Water Diver (UK)",
    rating: 5,
    date: "2026-08-14",
    comment: "Completed my Advanced Open Water course with instructor Tamer. His calm demeanor, deep knowledge of fish species, and focus on buoyancy made this the best trip ever. The Thistlegorm wreck dive was a bucket-list dream come true.",
    is_featured: true,
    status: "published",
    has_unpublished_changes: false,
  },
  {
    id: "rev-3",
    author_name: "Lukas & Elena Schmidt",
    author_title: "Certified Divers (Germany)",
    rating: 5,
    date: "2026-07-30",
    comment: "From the hotel pickup on time every single morning to the pristine Scubapro gear, everything was flawless. Small groups of 4 divers per guide meant we had quiet, relaxed dives away from crowded spots.",
    is_featured: true,
    status: "published",
    has_unpublished_changes: false,
  },
  {
    id: "rev-4",
    author_name: "Karim Al-Mansour",
    author_title: "Discover Scuba Beginner (UAE)",
    rating: 5,
    date: "2026-07-12",
    comment: "I was very nervous about diving for the first time, but the 1-on-1 instructor stayed with me every second underwater. Feeding fish and seeing sea turtles in crystal-clear water was magical. I am definitely coming back for the full Open Water course!",
    is_featured: true,
    status: "published",
    has_unpublished_changes: false,
  },
];

export const DEFAULT_FAQS: FAQ[] = [
  {
    id: "faq-pickup",
    question: "Do you offer free hotel pickups in Sharm El-Sheikh?",
    answer: "Yes! We provide complimentary round-trip air-conditioned transfers for all our diving trips and courses from any hotel or resort in Sharm El-Sheikh (Naama Bay, Nabq, Hadaba, Shark's Bay, and Ras Um Sid).",
    category: "Logistics & Transfers",
    display_order: 1,
    status: "published",
    has_unpublished_changes: false,
  },
  {
    id: "faq-beginner",
    question: "I have never dived before and can't swim very well. Can I still dive?",
    answer: "Absolutely! Our PADI Discover Scuba Diving (Introductory) experience requires no prior diving license. You are paired 1-on-1 with a certified PADI Master Instructor who controls your equipment and guides you gently up to a safe depth of 6 meters.",
    category: "Beginners & Courses",
    display_order: 2,
    status: "published",
    has_unpublished_changes: false,
  },
  {
    id: "faq-gear",
    question: "What equipment is included, and can I bring my own gear?",
    answer: "You are welcome to bring your own gear! We have secure, ventilated rinse and drying facilities. If you rent gear from us, we provide fully serviced, premium Scubapro and Aqualung BCDs, balanced regulators, 5mm wetsuits, and Mares fins.",
    category: "Equipment & Gear",
    display_order: 3,
    status: "published",
    has_unpublished_changes: false,
  },
  {
    id: "faq-national-park",
    question: "What are the national park fees and permissions?",
    answer: "For boat trips entering Ras Mohammed National Park or Straits of Tiran, the Egyptian Environmental Agency charges a mandatory marine reserve fee (approx. €7–€10 per person per day). This supports coral reef conservation and is settled onboard.",
    category: "Permits & Fees",
    display_order: 4,
    status: "published",
    has_unpublished_changes: false,
  },
  {
    id: "faq-nitrox",
    question: "Is Enriched Air Nitrox available for certified divers?",
    answer: "Yes! We offer 32% Nitrox fills for all certified Enriched Air divers. If you are not yet certified, you can easily complete the 1-day PADI Nitrox Specialty course with us during your holiday.",
    category: "Technical & Specialty",
    display_order: 5,
    status: "published",
    has_unpublished_changes: false,
  },
];
