import { BusinessSettings, ThemeConfig, HomepageSection, Activity, Course, Trip, GalleryItem, Review, FAQ } from "./types";
import { THEME_PRESETS } from "./theme-presets";

// ==============================================================================
// SINGLE AUTHORITATIVE SOURCE OF TRUTH FOR BUSINESS CONFIGURATION
// ==============================================================================

export const AUTHORITATIVE_BUSINESS_NAME =
  process.env.NEXT_PUBLIC_BUSINESS_NAME || "Diving Vision Center";

export const DEFAULT_BUSINESS_SETTINGS: BusinessSettings = {
  business_name: AUTHORITATIVE_BUSINESS_NAME,
  tagline: "Bespoke Scuba Diving Expeditions & Master Instruction",
  description: "Premier international diving sanctuary offering certified PADI & SSI instruction, private guided reef dives, and luxury boat safaris in pristine waters.",
  logo_url: "",
  favicon_url: "",
  phone: "+20 100 892 4410",
  whatsapp_number: "201008924410",
  whatsapp_default_message: `Hello ${AUTHORITATIVE_BUSINESS_NAME}, I would like to inquire about booking a diving experience.`,
  whatsapp_config: {
    phone_number: "201008924410",
    button_label: "Chat With Us",
    default_message: `Hello ${AUTHORITATIVE_BUSINESS_NAME}, I would like to inquire about booking a diving experience.`,
    is_enabled: true,
    position: "bottom-right",
    animation_intensity: "subtle",
    show_on_mobile: true,
    show_on_desktop: true,
  },
  email: "concierge@divingvisioncenter.com",
  address: "Marina Promenade, Royal Bay",
  city: "Sharm El Sheikh",
  country: "Egypt",
  google_maps_url: "https://maps.google.com",
  currency: "EUR",
  opening_hours: [
    { days: "Monday – Sunday", hours: "07:30 – 19:00" },
    { days: "Night Dives", hours: "19:30 – 22:00 (By Reservation)" },
  ],
  social_links: {
    instagram: "https://instagram.com",
    facebook: "https://facebook.com",
    tiktok: "https://tiktok.com",
    tripadvisor: "https://tripadvisor.com",
  },
  last_published_at: "2026-09-10T00:00:00.000Z",
  last_modified_at: "2026-09-10T00:00:00.000Z",
  has_unpublished_changes: false,
};

export const DEFAULT_HOMEPAGE_SECTIONS: HomepageSection[] = [
  {
    id: "sec-hero",
    section_key: "hero",
    name: "Cinematic Hero",
    title: "Descend into Pure Silence.",
    subtitle: "Experience luxury marine safaris and elite training in the world's most pristine coral reefs.",
    badge: "Bespoke Diving Expeditions",
    is_enabled: true,
    display_order: 1,
    has_unpublished_changes: false,
    settings: {
      water_temp: "27.5°C / 81°F",
      visibility: "35m+ Crystal",
      guide_ratio: "1 : 2 Private",
      gear_tier: "Scubapro Pro",
    },
  },
  {
    id: "sec-narrative",
    section_key: "narrative",
    name: "Brand Philosophy & Craft",
    title: "Where oceanic majesty meets understated precision.",
    subtitle: "We believe diving should be an unhurried, private, and deeply transformative encounter with the deep.",
    badge: "The Sanctuary Standard",
    is_enabled: true,
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "sec-activities",
    section_key: "activities",
    name: "Featured Experiences",
    title: "Curated Diving Experiences",
    subtitle: "From private house-reef immersion to nocturnal fluorescence expeditions.",
    badge: "Signature Dives",
    is_enabled: true,
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "sec-courses",
    section_key: "courses",
    name: "Certification & Academy",
    title: "International Master Training",
    subtitle: "World-recognized PADI & SSI certifications with private 1:2 instructor ratios.",
    badge: "Diver Education",
    is_enabled: true,
    display_order: 4,
    has_unpublished_changes: false,
  },
  {
    id: "sec-trips",
    section_key: "trips",
    name: "Expeditions & Safaris",
    title: "Day Expeditions & Liveaboards",
    subtitle: "Explore remote drop-offs, historic shipwrecks, and protected marine reserves.",
    badge: "Sea Voyages",
    is_enabled: true,
    display_order: 5,
    has_unpublished_changes: false,
  },
  {
    id: "sec-why-us",
    section_key: "why-us",
    name: "Why Choose Us",
    title: "Engineered for Safety & Serenity",
    subtitle: "Every detail designed around personal space, elite equipment, and marine conservation.",
    badge: "The Difference",
    is_enabled: true,
    display_order: 6,
    has_unpublished_changes: false,
  },
  {
    id: "sec-gallery",
    section_key: "gallery",
    name: "Visual Gallery",
    title: "Through the Lens of the Deep",
    subtitle: "Unretouched moments captured across our signature dive sites.",
    badge: "Underwater Gallery",
    is_enabled: true,
    display_order: 7,
    has_unpublished_changes: false,
  },
  {
    id: "sec-reviews",
    section_key: "reviews",
    name: "Guest Testimonials",
    title: "Voices from the Depths",
    subtitle: "Authentic reviews from divers, certified students, and private charter guests.",
    badge: "Verified Experiences",
    is_enabled: true,
    display_order: 8,
    has_unpublished_changes: false,
  },
  {
    id: "sec-faqs",
    section_key: "faqs",
    name: "Frequently Asked Questions",
    title: "Everything You Need to Know",
    subtitle: "Clear answers regarding logistics, medical requirements, gear, and booking policies.",
    badge: "Guest Inquiries",
    is_enabled: true,
    display_order: 9,
    has_unpublished_changes: false,
  },
  {
    id: "sec-booking",
    section_key: "booking",
    name: "Reservation & Concierge",
    title: "Begin Your Descent",
    subtitle: "Reserve your private dive slot or consult with our master expedition planners.",
    badge: "Direct Inquiry",
    is_enabled: true,
    display_order: 10,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    title: "Private House Reef Guided Dive",
    slug: "private-house-reef-guided-dive",
    short_description: "An unhurried dive along our protected drop-off with your dedicated master guide.",
    description: "Experience the vibrant biodiversity of our marine reserve in an intimate setting. With maximum visibility and zero boat transit time, this experience is tailored to your pacing and photography preferences.",
    featured_image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1400&auto=format&fit=crop",
    gallery_images: [
      "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?q=80&w=1200&auto=format&fit=crop"
    ],
    duration: "2 Hours (45-60 min submerged)",
    depth_max: "18m / 60ft",
    experience_level: "All Levels",
    price: 85,
    price_note: "Includes full premium gear set & dive computer",
    included_items: ["Dedicated PADI Master Guide", "Aqualung / Scubapro Gear Set", "High-oxygen 12L Aluminum Tank", "Post-dive towel & refreshments"],
    requirements: ["Valid Scuba Certification or recent refresher", "Completed medical questionnaire"],
    is_featured: true,
    status: "published",
    display_order: 1,
    has_unpublished_changes: false,
  },
  {
    id: "act-2",
    title: "Nocturnal Fluorescent Coral Dive",
    slug: "nocturnal-fluorescent-coral-dive",
    short_description: "Witness the underwater world illuminate in ultraviolet neon under custom blue-light torches.",
    description: "Using specialized UV lights and barrier filters on your mask, you will observe the bio-fluorescence emitted by living corals, anemones, and camouflaged night predators.",
    featured_image: "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?q=80&w=1400&auto=format&fit=crop",
    gallery_images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop"
    ],
    duration: "2.5 Hours",
    depth_max: "14m / 45ft",
    experience_level: "Intermediate",
    price: 110,
    price_note: "Includes specialized UV torches & yellow barrier masks",
    included_items: ["Fluorescence Light System", "Primary + Backup Night Torches", "Private Guide (1:2 ratio)", "Hot herbal tea on return"],
    requirements: ["Advanced Open Water or Night Diver specialty", "Minimum 15 logged open water dives"],
    is_featured: true,
    status: "published",
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "act-3",
    title: "Deep Wall Drift Exploration",
    slug: "deep-wall-drift-exploration",
    short_description: "Ride clear ocean currents along vertical underwater walls with pelagic marine life.",
    description: "A dramatic drift dive for experienced divers along sheer drop-offs with high probability of schooling jacks, barracudas, and rays.",
    featured_image: "https://images.unsplash.com/photo-1560275619-4662e36fa65c?q=80&w=1400&auto=format&fit=crop",
    gallery_images: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop"
    ],
    duration: "3 Hours",
    depth_max: "30m / 100ft",
    experience_level: "Advanced",
    price: 135,
    price_note: "Nitrox 32% included for certified divers",
    included_items: ["Zodiac boat transfer & surface support", "EANx32 Nitrox tank", "Surface Marker Buoy (SMB)", "Expert drift briefing"],
    requirements: ["PADI Advanced Open Water (or equivalent)", "Deep Dive certification", "Minimum 25 logged dives"],
    is_featured: true,
    status: "published",
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "act-4",
    title: "Underwater Photography & Macro Safari",
    slug: "underwater-photography-macro-safari",
    short_description: "Slow-paced dives dedicated to nudibranchs, seahorses, and macro photography composition.",
    description: "Designed specifically for photographers with zero rush. Extended bottom times with dedicated spotters skilled at finding rare macro marine subjects.",
    featured_image: "https://images.unsplash.com/photo-1580019542155-247062e19ce4?q=80&w=1400&auto=format&fit=crop",
    gallery_images: [],
    duration: "Half Day",
    depth_max: "15m / 50ft",
    experience_level: "Intermediate",
    price: 120,
    price_note: "Includes private macro spotter guide",
    included_items: ["Dedicated macro specialist guide", "Camera rinse and pressurized dry station", "Extended bottom time profile"],
    requirements: ["Excellent buoyancy control", "Open Water Diver or higher"],
    is_featured: false,
    status: "published",
    display_order: 4,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_COURSES: Course[] = [
  {
    id: "crs-1",
    title: "PADI Discover Scuba Diving Experience",
    slug: "padi-discover-scuba-diving",
    certification_agency: "PADI",
    level: "Beginner",
    short_description: "Your seamless introduction to breathing underwater in clear shallow lagoons.",
    description: "No prior experience required. Under direct master instructor supervision, learn fundamental safety skills and make your first ocean dive.",
    featured_image: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?q=80&w=1400&auto=format&fit=crop",
    duration: "1 Day",
    minimum_age: 10,
    prerequisites: "Basic swimming comfort & medical form",
    max_depth: "12m / 40ft",
    price: 140,
    price_note: "Can be credited towards full Open Water certification",
    learning_outcomes: [
      "Basic equipment operation & regulator clearing",
      "Mask clearing & underwater equalizing techniques",
      "Buoyancy fundamentals & hand signals",
      "One full guided open water dive"
    ],
    certification_card_included: false,
    gear_included: true,
    is_featured: true,
    status: "published",
    display_order: 1,
    has_unpublished_changes: false,
  },
  {
    id: "crs-2",
    title: "PADI Open Water Diver Certification",
    slug: "padi-open-water-diver",
    certification_agency: "PADI",
    level: "Beginner",
    short_description: "The gold-standard international scuba certification. Valid worldwide for a lifetime.",
    description: "Complete your theory online with PADI eLearning, followed by confined water skill mastery and 4 ocean training dives. Certifies you to dive to 18 meters autonomously.",
    featured_image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1400&auto=format&fit=crop",
    duration: "3 to 4 Days",
    minimum_age: 10,
    prerequisites: "Able to swim 200m and float/tread water for 10 minutes",
    max_depth: "18m / 60ft",
    price: 460,
    price_note: "Includes digital PADI e-Learning materials and digital cert card",
    learning_outcomes: [
      "Complete dive physics and decompression theory",
      "Mastery of 24 scuba safety skills in confined water",
      "4 Open water ocean training dives",
      "Lifetime digital PADI international certification"
    ],
    certification_card_included: true,
    gear_included: true,
    is_featured: true,
    status: "published",
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "crs-3",
    title: "PADI Advanced Open Water Diver",
    slug: "padi-advanced-open-water",
    certification_agency: "PADI",
    level: "Continuing Education",
    short_description: "Expand your depth limits to 30m, master underwater navigation, and refine trim.",
    description: "Fine-tune your skills across 5 specialized adventure dives: Deep Dive, Underwater Navigation, Peak Performance Buoyancy, Night Dive, and Wreck Exploration.",
    featured_image: "https://images.unsplash.com/photo-1560275619-4662e36fa65c?q=80&w=1400&auto=format&fit=crop",
    duration: "2 to 3 Days (5 Adventure Dives)",
    minimum_age: 12,
    prerequisites: "PADI Open Water Diver or equivalent certification",
    max_depth: "30m / 100ft",
    price: 410,
    price_note: "All 5 training dives conducted from custom dive vessels",
    learning_outcomes: [
      "Deep dive physiology and gas management down to 30m",
      "Precision compass and natural feature navigation",
      "Neutral buoyancy control and air consumption reduction",
      "Digital cert qualifying you for deep ocean charters"
    ],
    certification_card_included: true,
    gear_included: true,
    is_featured: true,
    status: "published",
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "crs-4",
    title: "PADI Enriched Air (Nitrox) Specialty",
    slug: "padi-enriched-air-nitrox",
    certification_agency: "PADI",
    level: "Specialty",
    short_description: "Extend your bottom time and reduce surface intervals with enriched oxygen gas blends.",
    description: "Learn to analyze gas blends, calculate oxygen exposure, and program your dive computer for enriched air mixes up to 40% O2.",
    featured_image: "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?q=80&w=1400&auto=format&fit=crop",
    duration: "1 Day",
    minimum_age: 12,
    prerequisites: "Open Water Diver or higher",
    max_depth: "Based on certification level",
    price: 190,
    price_note: "Includes digital materials and oxygen analyzer training",
    learning_outcomes: [
      "Oxygen analysis of cylinder contents",
      "Setting dive computers for custom Nitrox blends (22%-40%)",
      "Managing oxygen exposure and maximum operating depths (MOD)"
    ],
    certification_card_included: true,
    gear_included: false,
    is_featured: false,
    status: "published",
    display_order: 4,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_TRIPS: Trip[] = [
  {
    id: "trp-1",
    title: "Ras Mohammed Marine Reserve Day Safari",
    slug: "ras-mohammed-marine-reserve-day-safari",
    destination: "Shark & Yolanda Reefs, Red Sea",
    boat_name: "Custom 32m Catamaran Cruiser",
    description: "A full-day luxury yacht expedition to Shark and Yolanda Reefs. Witness sheer underwater drop-offs descending hundreds of meters, giant gorgonian fans, and pelagic activity.",
    featured_image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1400&auto=format&fit=crop",
    gallery_images: [
      "https://images.unsplash.com/photo-1560275619-4662e36fa65c?q=80&w=1200&auto=format&fit=crop"
    ],
    duration: "Full Day (08:00 – 16:30)",
    departure_time: "08:00 AM",
    return_time: "04:30 PM",
    price: 165,
    dives_included: 2,
    meals_included: ["Gourmet Buffet Lunch on Board", "Artisan Coffee & Pastries", "Fresh Fruit Refreshments"],
    itinerary: [
      { time: "08:00", activity: "Boarding & welcome briefing at marina jetty" },
      { time: "09:30", activity: "Dive 1: Shark Reef drop-off & drift" },
      { time: "11:30", activity: "Fresh Mediterranean buffet lunch on sundeck" },
      { time: "13:30", activity: "Dive 2: Yolanda Reef & cargo exploration" },
      { time: "15:30", activity: "Scenic cruise back to marina" }
    ],
    is_featured: true,
    status: "published",
    display_order: 1,
    has_unpublished_changes: false,
  },
  {
    id: "trp-2",
    title: "SS Thistlegorm Historical Wreck Expedition",
    slug: "ss-thistlegorm-historical-wreck-expedition",
    destination: "Straits of Gubal",
    boat_name: "Sovereign Cruiser",
    description: "Dive into one of the world's greatest underwater museums. Explore the WWII British cargo ship carrying locomotives, Bedford trucks, Norton motorcycles, and aircraft wings resting at 30m.",
    featured_image: "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?q=80&w=1400&auto=format&fit=crop",
    gallery_images: [],
    duration: "Full Day (05:30 – 17:00)",
    departure_time: "05:30 AM",
    return_time: "05:00 PM",
    price: 210,
    dives_included: 2,
    meals_included: ["Full Hot Breakfast", "Buffet Lunch", "All-day snacks & beverages"],
    itinerary: [
      { time: "05:30", activity: "Early sunrise departure to beat crowds" },
      { time: "08:30", activity: "Dive 1: Exterior wreck orientation & deck cargo" },
      { time: "11:00", activity: "Dive 2: Interior penetration of cargo holds No. 1 & 2" },
      { time: "12:30", activity: "Post-dive feast & decompression on sundeck" },
      { time: "17:00", activity: "Arrival at Marina Promenade" }
    ],
    is_featured: true,
    status: "published",
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "trp-3",
    title: "Straits of Tiran Reefs VIP Voyage",
    slug: "straits-of-tiran-reefs-vip-voyage",
    destination: "Jackson, Woodhouse, Thomas & Gordon Reefs",
    boat_name: "Catamaran Cruiser",
    description: "Experience pristine coral gardens and drift through the narrow straits separating Sinai from Saudi Arabia. Famous for encounters with hammerhead sharks and sea turtles.",
    featured_image: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?q=80&w=1400&auto=format&fit=crop",
    gallery_images: [],
    duration: "Full Day (08:30 – 16:30)",
    departure_time: "08:30 AM",
    return_time: "04:30 PM",
    price: 155,
    dives_included: 2,
    meals_included: ["Chef-Prepared Lunch", "Fresh Juice Bar", "Unlimited espresso & teas"],
    itinerary: [
      { time: "08:30", activity: "Departure from marina with safety briefing" },
      { time: "10:00", activity: "Dive 1: Jackson Reef wall dive" },
      { time: "12:00", activity: "Lunch in sheltered lagoon anchorage" },
      { time: "13:45", activity: "Dive 2: Woodhouse or Thomas Reef drift" },
      { time: "16:30", activity: "Return to port" }
    ],
    is_featured: true,
    status: "published",
    display_order: 3,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_GALLERY: GalleryItem[] = [
  {
    id: "gal-1",
    title: "Vibrant Coral Plateau at 14m",
    caption: "Pristine Acropora corals with anthias cloud in crystal-clear water.",
    image_url: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop",
    category: "Reef",
    location: "Yolanda Reef",
    status: "published",
    display_order: 1,
    has_unpublished_changes: false,
  },
  {
    id: "gal-2",
    title: "Green Sea Turtle Feeding in Seagrass Lagoon",
    caption: "Resident Chelonia mydas grazing quietly in shallow bay.",
    image_url: "https://images.unsplash.com/photo-1682687220063-4742bd7fd538?q=80&w=1200&auto=format&fit=crop",
    category: "Marine Life",
    location: "Marsa Bareika",
    status: "published",
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "gal-3",
    title: "Diver Exploring WWII Cargo Hold",
    caption: "Sunlight piercing through the deck opening of historic wreck.",
    image_url: "https://images.unsplash.com/photo-1582967788606-a171c1080cb0?q=80&w=1200&auto=format&fit=crop",
    category: "Wrecks",
    location: "SS Thistlegorm",
    status: "published",
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "gal-4",
    title: "Spotted Eagle Ray Gliding Along Wall",
    caption: "A magnificent Aetobatus narinari soaring in the blue abyss.",
    image_url: "https://images.unsplash.com/photo-1560275619-4662e36fa65c?q=80&w=1200&auto=format&fit=crop",
    category: "Marine Life",
    location: "Shark Observatory",
    status: "published",
    display_order: 4,
    has_unpublished_changes: false,
  },
  {
    id: "gal-5",
    title: "Catamaran Sundeck at Anchor",
    caption: "Custom dive vessel resting in calm turquoise bay after morning dives.",
    image_url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop",
    category: "Expeditions",
    location: "Straits of Tiran",
    status: "published",
    display_order: 5,
    has_unpublished_changes: false,
  },
  {
    id: "gal-6",
    title: "Macro Shot of Clownfish in Sea Anemone",
    caption: "Magnificent anemonefish displaying defensive colors under macro lighting.",
    image_url: "https://images.unsplash.com/photo-1580019542155-247062e19ce4?q=80&w=1200&auto=format&fit=crop",
    category: "Marine Life",
    location: "House Reef Sanctuary",
    status: "published",
    display_order: 6,
    has_unpublished_changes: false,
  },
];

export const DEFAULT_REVIEWS: Review[] = [
  {
    id: "rev-1",
    author_name: "Alexander von Berg",
    author_avatar: "",
    diver_certification: "PADI Master Scuba Diver",
    rating: 5,
    review_text: "Unquestionably the most refined dive operation in the region. The private guides are deeply knowledgeable marine scientists, and the gear was brand new Scubapro. Zero rush, impeccable safety standards.",
    trip_or_course: "Ras Mohammed Day Safari",
    date: "2026-08-14",
    source: "Verified Guest",
    is_verified: true,
    is_featured: true,
    status: "published",
    has_unpublished_changes: false,
  },
  {
    id: "rev-2",
    author_name: "Elena Rostova",
    author_avatar: "",
    diver_certification: "PADI Open Water Diver",
    rating: 5,
    review_text: "I was initially very nervous about breathing underwater. The instructor's patience and calm guidance made all the difference. Learning in a 1:2 ratio felt luxurious and completely safe. I am now certified and in love with the ocean!",
    trip_or_course: "PADI Open Water Diver Course",
    date: "2026-07-29",
    source: "Verified Guest",
    is_verified: true,
    is_featured: true,
    status: "published",
    has_unpublished_changes: false,
  },
  {
    id: "rev-3",
    author_name: "Marcus Thorne",
    author_avatar: "",
    diver_certification: "Technical Diver",
    rating: 5,
    review_text: "The Thistlegorm wreck charter was exceptional. Early sunrise arrival meant we had the entire wreck to ourselves before other boats showed up. The vessel chef prepared 5-star meals. Worth every euro.",
    trip_or_course: "SS Thistlegorm Wreck Expedition",
    date: "2026-07-10",
    source: "Verified Guest",
    is_verified: true,
    is_featured: true,
    status: "published",
    has_unpublished_changes: false,
  },
];

export const DEFAULT_FAQS: FAQ[] = [
  {
    id: "faq-1",
    question: "Do I need prior diving experience to join a dive or safari?",
    answer: "No prior experience is necessary for our 'Discover Scuba Diving' experience or beginner snorkeling excursions. For certified dive trips (e.g., Ras Mohammed walls or Thistlegorm wreck), a valid PADI, SSI, or equivalent certification card with proof of logged dives is required.",
    category: "General",
    status: "published",
    display_order: 1,
    has_unpublished_changes: false,
  },
  {
    id: "faq-2",
    question: "What is included with equipment rental?",
    answer: "All our rental gear consists of current-season premium Aqualung and Scubapro equipment: balanced diaphragm regulators, integrated weight BCDs, 5mm/3mm wetsuits, frameless silicone masks, and modern Suunto/Mares dive computers.",
    category: "Equipment & Safety",
    status: "published",
    display_order: 2,
    has_unpublished_changes: false,
  },
  {
    id: "faq-3",
    question: "What is your guide-to-diver ratio?",
    answer: "We uphold a strict maximum ratio of 1 guide to 4 divers for certified groups, and 1 instructor to 2 students for training courses. Private 1:1 VIP guides are also available upon reservation.",
    category: "Equipment & Safety",
    status: "published",
    display_order: 3,
    has_unpublished_changes: false,
  },
  {
    id: "faq-4",
    question: "How far in advance should I book my expedition?",
    answer: "Due to limited daily capacity to preserve marine habitats and avoid crowding, we recommend reserving your date at least 3 to 7 days in advance, especially for Thistlegorm charters and private boat buyouts.",
    category: "Trips & Booking",
    status: "published",
    display_order: 4,
    has_unpublished_changes: false,
  },
  {
    id: "faq-5",
    question: "What is your cancellation and weather policy?",
    answer: "If port authorities suspend marine departures due to unseasonal winds, you will receive a 100% full refund or complimentary reschedule. Private cancellations made at least 48 hours in advance incur no penalty.",
    category: "Trips & Booking",
    status: "published",
    display_order: 5,
    has_unpublished_changes: false,
  },
];
