import { ThemeConfig } from "./types";

export const THEME_PRESETS: Record<string, ThemeConfig> = {
  "premium-ocean": {
    id: "theme-premium-ocean",
    name: "Premium Ocean",
    preset_key: "premium-ocean",
    colors: {
      background: "#040914",
      surface: "#081426",
      surface_elevated: "#0f2038",
      primary: "#0ea5e9",
      primary_glow: "rgba(14, 165, 233, 0.4)",
      secondary: "#06b6d4",
      accent: "#38bdf8",
      text_primary: "#f8fafc",
      text_muted: "#94a3b8",
      border_subtle: "rgba(255, 255, 255, 0.08)",
    },
    typography: {
      heading_font: "font-display",
      body_font: "font-sans",
      letter_spacing: "-0.025em",
    },
    styling: {
      border_radius: "lg",
      button_style: "pill",
      card_style: "glass",
      nav_style: "floating-glass",
      hero_style: "cinematic-full",
      section_spacing: "spacious",
      glass_intensity: "medium",
      dark_mode: true,
    },
    is_active: true,
  },
  "luxury-black": {
    id: "theme-luxury-black",
    name: "Luxury Black",
    preset_key: "luxury-black",
    colors: {
      background: "#050507",
      surface: "#0d0e12",
      surface_elevated: "#161820",
      primary: "#f8fafc",
      primary_glow: "rgba(248, 250, 252, 0.25)",
      secondary: "#94a3b8",
      accent: "#38bdf8",
      text_primary: "#ffffff",
      text_muted: "#71717a",
      border_subtle: "rgba(255, 255, 255, 0.06)",
    },
    typography: {
      heading_font: "font-sans",
      body_font: "font-sans",
      letter_spacing: "-0.03em",
    },
    styling: {
      border_radius: "md",
      button_style: "pill",
      card_style: "solid",
      nav_style: "floating-glass",
      hero_style: "cinematic-full",
      section_spacing: "spacious",
      glass_intensity: "subtle",
      dark_mode: true,
    },
    is_active: false,
  },
  "red-sea-adventure": {
    id: "theme-red-sea-adventure",
    name: "Red Sea Adventure",
    preset_key: "red-sea-adventure",
    colors: {
      background: "#03121d",
      surface: "#072033",
      surface_elevated: "#0c314d",
      primary: "#06b6d4",
      primary_glow: "rgba(6, 182, 212, 0.45)",
      secondary: "#38bdf8",
      accent: "#f59e0b",
      text_primary: "#f0fdfa",
      text_muted: "#99f6e4",
      border_subtle: "rgba(6, 182, 212, 0.15)",
    },
    typography: {
      heading_font: "font-display",
      body_font: "font-sans",
      letter_spacing: "-0.02em",
    },
    styling: {
      border_radius: "xl",
      button_style: "rounded",
      card_style: "glass",
      nav_style: "floating-glass",
      hero_style: "cinematic-full",
      section_spacing: "normal",
      glass_intensity: "heavy",
      dark_mode: true,
    },
    is_active: false,
  },
  "minimal-white": {
    id: "theme-minimal-white",
    name: "Minimal White",
    preset_key: "minimal-white",
    colors: {
      background: "#f8fafc",
      surface: "#ffffff",
      surface_elevated: "#f1f5f9",
      primary: "#0284c7",
      primary_glow: "rgba(2, 132, 199, 0.25)",
      secondary: "#0369a1",
      accent: "#0ea5e9",
      text_primary: "#0f172a",
      text_muted: "#64748b",
      border_subtle: "rgba(0, 0, 0, 0.08)",
    },
    typography: {
      heading_font: "font-sans",
      body_font: "font-sans",
      letter_spacing: "-0.02em",
    },
    styling: {
      border_radius: "lg",
      button_style: "rounded",
      card_style: "bordered",
      nav_style: "floating-glass",
      hero_style: "cinematic-full",
      section_spacing: "spacious",
      glass_intensity: "subtle",
      dark_mode: false,
    },
    is_active: false,
  },
  custom: {
    id: "theme-custom",
    name: "Custom Bespoke",
    preset_key: "custom",
    colors: {
      background: "#060b13",
      surface: "#0c1726",
      surface_elevated: "#13233a",
      primary: "#0ea5e9",
      primary_glow: "rgba(14, 165, 233, 0.4)",
      secondary: "#06b6d4",
      accent: "#38bdf8",
      text_primary: "#f8fafc",
      text_muted: "#94a3b8",
      border_subtle: "rgba(255, 255, 255, 0.08)",
    },
    typography: {
      heading_font: "font-display",
      body_font: "font-sans",
      letter_spacing: "-0.02em",
    },
    styling: {
      border_radius: "lg",
      button_style: "pill",
      card_style: "glass",
      nav_style: "floating-glass",
      hero_style: "cinematic-full",
      section_spacing: "spacious",
      glass_intensity: "medium",
      dark_mode: true,
    },
    is_active: false,
  },
};
